#!/bin/bash

cd /Users/danfengwu/Documents/Riboseq/sequencing_submit/2020_8_31/Ribosome_occupancy_distribution/Ribo/miRNA

Rscript deseq2_pca_bin_1.R
Rscript deseq2_pca_bin_2.R
Rscript deseq2_pca_bin_3.R
Rscript deseq2_pca_bin_4.R
Rscript deseq2_pca_bin_5.R
Rscript deseq2_pca_bin_6.R
Rscript deseq2_pca_bin_7.R
Rscript deseq2_pca_bin_8.R
Rscript deseq2_pca_bin_9.R
Rscript deseq2_pca_bin_10.R
Rscript deseq2_pca_bin_11.R
Rscript deseq2_pca_bin_12.R
Rscript deseq2_pca_bin_13.R
Rscript deseq2_pca_bin_14.R
Rscript deseq2_pca_bin_15.R
Rscript deseq2_pca_bin_16.R
Rscript deseq2_pca_bin_17.R
Rscript deseq2_pca_bin_18.R
Rscript deseq2_pca_bin_19.R
Rscript deseq2_pca_bin_20.R
Rscript deseq2_pca_bin_21.R
Rscript deseq2_pca_bin_22.R
Rscript deseq2_pca_bin_23.R
Rscript deseq2_pca_bin_24.R
Rscript deseq2_pca_bin_25.R
Rscript deseq2_pca_bin_26.R
Rscript deseq2_pca_bin_27.R
Rscript deseq2_pca_bin_28.R
Rscript deseq2_pca_bin_29.R
Rscript deseq2_pca_bin_30.R
Rscript deseq2_pca_bin_31.R
Rscript deseq2_pca_bin_32.R
Rscript deseq2_pca_bin_33.R
Rscript deseq2_pca_bin_34.R
Rscript deseq2_pca_bin_35.R
Rscript deseq2_pca_bin_36.R
Rscript deseq2_pca_bin_37.R
Rscript deseq2_pca_bin_38.R
Rscript deseq2_pca_bin_39.R
Rscript deseq2_pca_bin_40.R
Rscript deseq2_pca_bin_41.R
Rscript deseq2_pca_bin_42.R
Rscript deseq2_pca_bin_43.R
Rscript deseq2_pca_bin_44.R
Rscript deseq2_pca_bin_45.R
Rscript deseq2_pca_bin_46.R
Rscript deseq2_pca_bin_47.R
Rscript deseq2_pca_bin_48.R
Rscript deseq2_pca_bin_49.R
Rscript deseq2_pca_bin_50.R
Rscript deseq2_pca_bin_51.R
Rscript deseq2_pca_bin_52.R
Rscript deseq2_pca_bin_53.R
Rscript deseq2_pca_bin_54.R
Rscript deseq2_pca_bin_55.R
Rscript deseq2_pca_bin_56.R
Rscript deseq2_pca_bin_57.R
Rscript deseq2_pca_bin_58.R
Rscript deseq2_pca_bin_59.R
Rscript deseq2_pca_bin_60.R

